# Generated by Django 5.0.7 on 2024-10-06 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-Абонемента')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Название абонемента')),
                ('membership_photo', models.ImageField(upload_to='images/', verbose_name='Фото-абонемента')),
                ('price', models.IntegerField(unique=True, verbose_name='Цена')),
                ('desc_membership', models.TextField(blank=True, max_length=255, unique=True, verbose_name='Описание абонемента')),
                ('about_membership', models.TextField(blank=True, max_length=559, verbose_name='О абонементе')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CardAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Картинка карточки')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_time', models.TimeField(auto_now_add=True, null=True)),
                ('end_time', models.TimeField(auto_now_add=True, null=True)),
                ('membership_type_allow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gym.membership', verbose_name='Абонемент для занятия')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.IntegerField(unique=True, verbose_name='Телефон')),
                ('profile_photo', models.ImageField(upload_to='images/', verbose_name='Фото-профиля')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-trainer')),
                ('classes_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='gym.cardabout', verbose_name='Занятия')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренера',
                'ordering': ['id', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('phone', models.IntegerField(unique=True, verbose_name='Телефон')),
                ('membership_start_date', models.DateTimeField(auto_now_add=True, verbose_name='Присоединился(ась)')),
                ('membership_end_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата окончания')),
                ('profile_photo', models.ImageField(upload_to='images/', verbose_name='Фото-профиля')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('membership_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gym.membership', verbose_name='Тип абонемента')),
                ('trainer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gym.trainer', verbose_name='Прикрепленный тренер')),
            ],
            options={
                'verbose_name': 'Человекa',
                'verbose_name_plural': 'Людей',
                'ordering': ['first_name'],
            },
        ),
        migrations.AddField(
            model_name='cardabout',
            name='trainer_classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gym.trainer', verbose_name='Тренер'),
        ),
        migrations.AddIndex(
            model_name='trainer',
            index=models.Index(fields=['first_name'], name='gym_trainer_first_n_ee7ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='members',
            index=models.Index(fields=['first_name'], name='gym_members_first_n_a9fca9_idx'),
        ),
        migrations.AddIndex(
            model_name='cardabout',
            index=models.Index(fields=['slug'], name='gym_cardabo_slug_892930_idx'),
        ),
    ]
