# Generated by Django 5.0.7 on 2024-10-09 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='is_actime',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
