# Generated by Django 5.0.7 on 2024-10-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_trainer_is_actime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='is_actime',
            new_name='is_active',
        ),
    ]
