# Generated by Django 5.0.7 on 2024-10-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_trainer_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='is_active',
            field=models.BooleanField(choices=[(0, 'Не тернирует'), (1, 'Тренирует')], default=0),
        ),
    ]
