# Generated by Django 5.0.7 on 2024-10-10 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0006_alter_cardabout_options_trainer_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='photo',
        ),
    ]
