# Generated by Django 5.0.7 on 2024-10-10 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_remove_trainer_photo'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='trainer',
            managers=[
            ],
        ),
    ]
