# Generated by Django 5.0.7 on 2024-10-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_trainer_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Фото-профиля'),
        ),
    ]
