# Generated by Django 5.0.7 on 2024-10-14 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_alter_members_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardabout',
            name='area_of_text',
            field=models.TextField(blank=True, verbose_name='Описание-на сайте'),
        ),
    ]
